spring:
  
  cloud:
  
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          
      bindings:
        input: 
          destination: topic1

          #content-type: plain/text
          group: group-id
        output: 
          destination: topic2
          #content-type: plain/text
      
        
