spring.application.name: consumer-kafka
spring.kafka.bootstrap-servers: localhost:9092
spring.kafka.consumer.group-id: consumerKafkaGroup
spring.kafka.consumer.auto-offset-reset: latest
spring.kafka.consumer.alert-topic: alert.json
spring.kafka.listener.concurrency: 2

management.endpoints.web.exposure.include: beans,env,health,info,metrics,mappings
management.endpoint.health.show-details: always

